CREATE SCHEMA IF NOT EXISTS loanmowerman;

CREATE TABLE IF NOT EXISTS loanmowerman.institutes (
    code LONGVARCHAR PRIMARY KEY,
    name LONGVARCHAR NOT NULL
);

CREATE SEQUENCE loanmowerman.loan_amounts_id_seq START WITH 1;

CREATE TABLE IF NOT EXISTS loanmowerman.loan_amounts (
    id BIGINT GENERATED BY DEFAULT AS SEQUENCE loanmowerman.loan_amounts_id_seq PRIMARY KEY,
    institute_code LONGVARCHAR NOT NULL,
    year INT NOT NULL,
    month INT NOT NULL,
    amount BIGINT NOT NULL,
    UNIQUE (institute_code, year, month),
    FOREIGN KEY (institute_code) REFERENCES loanmowerman.institutes(code)
);
